### ISSUE TITLE
Split samples by C++ version

### ISSUE THREAD

**Issue by edran** [sftrabbit/CppSamples-Samples#13]
Some samples are valid only for C++11 or C++14, so it might be a good idea to split the code and have different versions of each snippet.

**Comment by sftrabbit** [comment]
Samples can now be tagged with the C++ version they require. Where a sample may easily adapted to different versions, those versions are all tagged. C++ Samples doesn't intentionally provide pre-C++11 samples (unless they  just happen to be backwards compatible), so C++98 and C++03 are not tagged.
