### ISSUE TITLE
Add LICENSE to repository and website

### ISSUE THREAD

**Issue by edran** [sftrabbit/CppSamples-Samples#14]
It's probably worth to add a permissive license such as MIT or BSD on both the repository and at the bottom of the website (maybe a disclaimer?). It's probably not necessary to insert it in every snippet.

**Comment by sftrabbit** [comment]
Absolutely. Would love to hear people's suggestions. Honestly, I think putting them in the public domain is best - what's the best approach for that with code?

**Comment by edran** [comment]
Having a look at http://choosealicense.com/licenses/, it seems the best might be indeed Public Domain.

**Comment by edran** [comment]
CC0 is also recommended by the FSF: https://www.gnu.org/licenses/license-recommendations.html

**Comment by sftrabbit** [comment]
Added LICENSE.txt and notice to sample pages
