### ISSUE TITLE
Add "old-style" C++ for comparison

### ISSUE THREAD

**Issue by luizberti** [sftrabbit/CppSamples-Samples#26]
It would be cool to contrast the nice, modern examples with old, no-longer-a-good-way-to do it, other examples.

**Comment by ghost** [comment]
+1.

I can also see the value in some "this is a security vulnerability" examples.

**Comment by sftrabbit** [comment]
My personal opinion is that the sample description should point out any improvements this modern style has over earlier attempts. Perhaps more of the existing samples need this. I'd want to avoid showing bad examples at all (in case there is any confusion).

**Comment by thecoshman** [comment]
My initial reaction would be the same, why show  'bad' way of doing things?

Well, an obvious reason is to show what not to do.

Perhaps it needs to be managed in a different way though, some sort of "Samples of Modernising Old C++". There are some who have old code bases, but could work on upgrading, so I am sure they would appreciate seeing not just that the code is bad, as I am sure they know that, but how to update it.

I would definitely not muddy this collection with examples of old style C++. There are a lot of things that are done bad, even though earlier versions of C++ provided the tools for not doing such shameful things.

**Comment by luizberti** [comment]
My rationale comes from the rocks I hit while learning C/C++. It's an old language. Really old. Most resources for it are equally old, and it's hard to have updated ones, with modern features and what not.

You have a collection of samples of C++ that are modern, and if they are modern it's because there obviously were at some point, old, and worse ways to do it. The great thing about having this contrast with old examples would be a more descriptive way to explain _why_ the modern examples are modern. It would show what are the advantages of taking that route, and why we no longer do it the old way.

It would become a wonderful resource to update people from the old ages to updated tactics. Maybe add a toggle button that shows a side by side of good and bad, but the bad stays hidden by default. That way it wouldn't be confusing, since people would only see bad code if they clicked the button that says _"Show Bad Code"_ or something.
